version: 2

formats: all

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"


sphinx:
  configuration: source/conf.py
  fail_on_warning: false 

python: 
  install:
    - method: pip
      path: ./requirements.txt